### Dataset Link : https://www.kaggle.com/datasets/uciml/default-of-credit-card-clients-dataset

- ID: ID of each client
- LIMIT_BAL: Amount of given credit in NT dollars (includes individual and family/supplementary credit
- SEX: Gender (1=male, 2=female)
- EDUCATION: (1=graduate school, 2=university, 3=high school, 4=others, 5=unknown, 6=unknown)
- MARRIAGE: Marital status (1=married, 2=single, 3=others)
- AGE: Age in years
- PAY_0: Repayment status in September, 2005 (-1=pay duly, 1=payment delay for one month, 2=payment delay for two months, … 8=payment delay for eight months, 9=payment delay for - nine months and above)
- PAY_2: Repayment status in August, 2005 (scale same as above)
- PAY_3: Repayment status in July, 2005 (scale same as above)
- PAY_4: Repayment status in June, 2005 (scale same as above)
- PAY_5: Repayment status in May, 2005 (scale same as above)
- PAY_6: Repayment status in April, 2005 (scale same as above)
- BILL_AMT1: Amount of bill statement in September, 2005 (NT dollar)
- BILL_AMT2: Amount of bill statement in August, 2005 (NT dollar)
- BILL_AMT3: Amount of bill statement in July, 2005 (NT dollar)
- BILL_AMT4: Amount of bill statement in June, 2005 (NT dollar)
- BILL_AMT5: Amount of bill statement in May, 2005 (NT dollar)
- BILL_AMT6: Amount of bill statement in April, 2005 (NT dollar)
- PAY_AMT1: Amount of previous payment in September, 2005 (NT dollar)
- PAY_AMT2: Amount of previous payment in August, 2005 (NT dollar)
- PAY_AMT3: Amount of previous payment in July, 2005 (NT dollar)
- PAY_AMT4: Amount of previous payment in June, 2005 (NT dollar)
- PAY_AMT5: Amount of previous payment in May, 2005 (NT dollar)
- PAY_AMT6: Amount of previous payment in April, 2005 (NT dollar)
- default.payment.next.month: Default payment (1=yes, 0=no)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px

In [ ]:
# to show all columns
pd.set_option('display.max_columns', None)

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/credit_project/UCI_Credit_Card.csv').drop('ID', axis= 1)
df

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,20000.0,2,2,1,24,2,2,-1,-1,-2,-2,3913.0,3102.0,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,2,2,2,26,-1,2,0,0,0,2,2682.0,1725.0,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,2,2,2,34,0,0,0,0,0,0,29239.0,14027.0,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,2,2,1,37,0,0,0,0,0,0,46990.0,48233.0,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,1,2,1,57,-1,0,-1,0,0,0,8617.0,5670.0,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,1,3,1,39,0,0,0,0,0,0,188948.0,192815.0,208365.0,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,150000.0,1,3,2,43,-1,-1,-1,-1,0,0,1683.0,1828.0,3502.0,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,30000.0,1,2,2,37,4,3,2,-1,0,0,3565.0,3356.0,2758.0,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,80000.0,1,3,1,41,1,-1,0,0,0,-1,-1645.0,78379.0,76304.0,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,50000.0,1,2,1,46,0,0,0,0,0,0,47929.0,48905.0,49764.0,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

### Data Exploration

In [ ]:
# Check Data Types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   LIMIT_BAL                   30000 non-null  float64
 1   SEX                         30000 non-null  int64
 2   EDUCATION                   30000 non-null  int64
 3   MARRIAGE                    30000 non-null  int64
 4   AGE                         30000 non-null  int64
 5   PAY_0                       30000 non-null  int64
 6   PAY_2                       30000 non-null  int64
 7   PAY_3                       30000 non-null  int64
 8   PAY_4                       30000 non-null  int64
 9   PAY_5                       30000 non-null  int64
 10  PAY_6                       30000 non-null  int64
 11  BILL_AMT1                   30000 non-null  float64
 12  BILL_AMT2                   30000 non-null  float64
 13  BILL_AMT3                   30000 non-null  float64
 14  BILL_AMT4                   30000 non-null  float64
 15  BILL_AMT5                   30000 non-null  float64
 16  BILL_AMT6                   30000 non-null  float64
 17  PAY_AMT1                    30000 non-null  float64
 18  PAY_AMT2                    30000 non-null  float64
 19  PAY_AMT3                    30000 non-null  float64
 20  PAY_AMT4                    30000 non-null  float64
 21  PAY_AMT5                    30000 non-null  float64
 22  PAY_AMT6                    30000 non-null  float64
 23  default.payment.next.month  30000 non-null  int64
dtypes: float64(13), int64(11)
memory usage: 5.5 MB

In [ ]:
# Check summary statistics for Numerical cols
df.describe().round(2)

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
count,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00
mean,167484.32,1.60,1.85,1.55,35.49,-0.02,-0.13,-0.17,-0.22,-0.27,-0.29,51223.33,49179.08,47013.15,43262.95,40311.40,38871.76,5663.58,5921.16,5225.68,4826.08,4799.39,5215.50,0.22
std,129747.66,0.49,0.79,0.52,9.22,1.12,1.20,1.20,1.17,1.13,1.15,73635.86,71173.77,69349.39,64332.86,60797.16,59554.11,16563.28,23040.87,17606.96,15666.16,15278.31,17777.47,0.42
min,10000.00,1.00,0.00,0.00,21.00,-2.00,-2.00,-2.00,-2.00,-2.00,-2.00,-165580.00,-69777.00,-157264.00,-170000.00,-81334.00,-339603.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,50000.00,1.00,1.00,1.00,28.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,3558.75,2984.75,2666.25,2326.75,1763.00,1256.00,1000.00,833.00,390.00,296.00,252.50,117.75,0.00
50%,140000.00,2.00,2.00,2.00,34.00,0.00,0.00,0.00,0.00,0.00,0.00,22381.50,21200.00,20088.50,19052.00,18104.50,17071.00,2100.00,2009.00,1800.00,1500.00,1500.00,1500.00,0.00
75%,240000.00,2.00,2.00,2.00,41.00,0.00,0.00,0.00,0.00,0.00,0.00,67091.00,64006.25,60164.75,54506.00,50190.50,49198.25,5006.00,5000.00,4505.00,4013.25,4031.50,4000.00,0.00
max,1000000.00,2.00,6.00,3.00,79.00,8.00,8.00,8.00,8.00,8.00,8.00,964511.00,983931.00,1664089.00,891586.00,927171.00,961664.00,873552.00,1684259.00,896040.00,621000.00,426529.00,528666.00,1.00

In [ ]:
df.columns

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default.payment.next.month'],
      dtype='object')

1) SEX: Gender (1=male, 2=female)
2) EDUCATION: (1=graduate school, 2=university, 3=high school, 4=others ,5=unknown, 6=unknown)
3) MARRIAGE: Marital status (1=married, 2=single, 3=others)

In [ ]:
for col in ['SEX', 'EDUCATION', 'MARRIAGE']:
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('-' * 50)

SEX
2
[2 1]
--------------------------------------------------
EDUCATION
7
[2 1 3 5 4 6 0]
--------------------------------------------------
MARRIAGE
4
[1 2 3 0]
--------------------------------------------------

In [ ]:
# Check duplicates
df.duplicated().sum()

np.int64(35)

In [ ]:
# Drop duplicates
df.drop_duplicates(inplace= True, ignore_index= True)

In [ ]:
# Check missing values
df.isna().sum()

LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

### In depth check for numerical cols

In [ ]:
num_cols = df.select_dtypes(include= 'number').columns
num_cols

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default.payment.next.month'],
      dtype='object')

In [ ]:
for col in num_cols:
    px.histogram(data_frame= df, x= col, title= col).show()

Output hidden; open in https://colab.research.google.com to view.

# Data Cleaning

In [18]:
# fun to replace all value -2 and -1 with 0 "No delay"
def clean_pay_cols(x):

    if x in [-2, -1]:
        return 0

    else:
        return x

df[['PAY_0', 'PAY_2', 'PAY_3', 'PAY_4',	'PAY_5', 'PAY_6']] = df[['PAY_0', 'PAY_2', 'PAY_3', 'PAY_4',	'PAY_5', 'PAY_6']].applymap(clean_pay_cols)
df[['PAY_0', 'PAY_2', 'PAY_3', 'PAY_4',	'PAY_5', 'PAY_6']]

/tmp/ipykernel_5791/3158227144.py:9: FutureWarning:

DataFrame.applymap has been deprecated. Use DataFrame.map instead.

       PAY_0  PAY_2  PAY_3  PAY_4  PAY_5  PAY_6
0          2      2      0      0      0      0
1          0      2      0      0      0      2
2          0      0      0      0      0      0
3          0      0      0      0      0      0
4          0      0      0      0      0      0
...      ...    ...    ...    ...    ...    ...
29960      0      0      0      0      0      0
29961      0      0      0      0      0      0
29962      4      3      2      0      0      0
29963      1      0      0      0      0      0
29964      0      0      0      0      0      0

[29965 rows x 6 columns]

In [19]:
df.columns = df.columns.str.strip()
df.columns

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default.payment.next.month'],
      dtype='object')


#### EDUCATION: (1=graduate school, 2=university, 3=high school, 4=others ,5=unknown, 6=unknown)

In [20]:
def clean_edu(x):

    if x in ['Unknown', '0']:
        return 'Others'

    else:
        return x

df['EDUCATION'] = df['EDUCATION'].apply(clean_edu)
df['EDUCATION']

0        2
1        2
2        2
3        2
4        2
        ..
29960    3
29961    3
29962    2
29963    3
29964    2
Name: EDUCATION, Length: 29965, dtype: int64

#### MARRIAGE: Marital status (1=married, 2=single, 3=others)

In [21]:
def clean_marriage(x):

    if x == '0':
        return 'Other'

    else:
        return x

df['MARRIAGE'] = df['MARRIAGE'].apply(clean_marriage)
df['MARRIAGE']

0        1
1        2
2        2
3        1
4        1
        ..
29960    1
29961    2
29962    2
29963    1
29964    1
Name: MARRIAGE, Length: 29965, dtype: int64

In [22]:
df.head(5)

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,20000.0,2,2,1,24,2,2,0,0,0,0,3913.0,3102.0,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,2,2,2,26,0,2,0,0,0,2,2682.0,1725.0,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,2,2,2,34,0,0,0,0,0,0,29239.0,14027.0,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,2,2,1,37,0,0,0,0,0,0,46990.0,48233.0,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,1,2,1,57,0,0,0,0,0,0,8617.0,5670.0,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [25]:
corr_df = df.corr().round(2)
px.imshow(corr_df, text_auto= True, height= 800, width=1200).show()

### Data Preprocessing

### Split Data into Input features and Target variable

In [27]:
x = df.drop(['default.payment.next.month'], axis= 1)
y = df['default.payment.next.month']

### Split Data into Train & Test

In [28]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 42, stratify= y)

### Handle Numerical columns

In [29]:
scaling_cols = x_train.drop(['SEX', 'EDUCATION', 'MARRIAGE','PAY_0', 'PAY_2', 'PAY_3', 'PAY_4',	'PAY_5', 'PAY_6'], axis= 1).columns
scaling_cols

Index(['LIMIT_BAL', 'AGE', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4',
       'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3',
       'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6'],
      dtype='object')

In [30]:
from sklearn.preprocessing import RobustScaler

rc = RobustScaler()

x_train[scaling_cols] = rc.fit_transform(x_train[scaling_cols])
x_test[scaling_cols] = rc.transform(x_test[scaling_cols])

### Handle Categorical Columns

In [31]:
ohe_cols = ['SEX', 'MARRIAGE']
ohe_cols

['SEX', 'MARRIAGE']

In [32]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop= 'first', sparse_output= False)

ohe_train_arr = ohe.fit_transform(x_train[ohe_cols])
ohe_test_arr = ohe.transform(x_test[ohe_cols])

In [33]:
ohe_train_df = pd.DataFrame(ohe_train_arr, columns= ohe.get_feature_names_out())
ohe_test_df = pd.DataFrame(ohe_test_arr, columns= ohe.get_feature_names_out())

In [34]:
ohe_test_df

      SEX_2  MARRIAGE_1  MARRIAGE_2  MARRIAGE_3
0       1.0         1.0         0.0         0.0
1       0.0         1.0         0.0         0.0
2       1.0         0.0         1.0         0.0
3       1.0         0.0         1.0         0.0
4       0.0         0.0         1.0         0.0
...     ...         ...         ...         ...
5988    1.0         1.0         0.0         0.0
5989    1.0         1.0         0.0         0.0
5990    1.0         0.0         1.0         0.0
5991    1.0         0.0         1.0         0.0
5992    0.0         1.0         0.0         0.0

[5993 rows x 4 columns]

In [35]:
x_train.reset_index(inplace= True, drop= True)
x_test.reset_index(inplace= True, drop= True)

y_train.reset_index(inplace= True, drop= True)
y_test.reset_index(inplace= True, drop= True)

In [36]:
x_train = pd.concat([x_train, ohe_train_df], axis= 1).drop(ohe_cols, axis= 1)

x_test = pd.concat([x_test, ohe_test_df], axis= 1).drop(ohe_cols, axis= 1)

In [37]:
x_train

,LIMIT_BAL,EDUCATION,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,SEX_2,MARRIAGE_1,MARRIAGE_2,MARRIAGE_3
0,0.842105,2,0.076923,0,0,0,0,0,0,-0.352130,-0.351597,-0.351808,-0.366891,-0.373793,-0.356819,-0.523821,-0.484571,-0.442050,-0.400721,-0.400507,-0.387898,0.0,1.0,0.0,0.0
1,-0.473684,3,0.230769,2,2,2,2,2,2,0.391136,0.446347,0.504429,0.551254,0.180531,0.193976,0.049888,-0.122951,-0.442050,0.507580,-0.400507,-0.077580,1.0,0.0,0.0,1.0
2,-0.315789,1,-0.846154,0,0,0,0,0,0,-0.345208,-0.344352,-0.344100,-0.349917,-0.355574,-0.347573,-0.413071,-0.377531,-0.225834,-0.282108,-0.400507,-0.119472,0.0,0.0,1.0,0.0
3,-0.473684,2,-0.615385,0,0,0,0,0,0,-0.346050,-0.317686,-0.345038,-0.359436,-0.373793,-0.340577,-0.005488,-0.390550,-0.347090,-0.400721,-0.192244,-0.387898,1.0,0.0,1.0,0.0
4,0.315789,2,-0.307692,0,0,0,0,0,0,0.403857,0.463286,0.077881,1.992631,2.339849,2.334142,4.538289,5.516152,30.035427,4.358779,6.613444,0.736747,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23967,-0.684211,1,0.307692,0,0,0,0,0,0,-0.224479,-0.240953,-0.345038,-0.359436,-0.373793,-0.340577,-0.274383,-0.390550,-0.347090,-0.400721,-0.192244,-0.387898,0.0,0.0,1.0,0.0
23968,-0.421053,2,-0.769231,0,0,0,0,0,0,-0.264078,-0.151361,-0.351808,-0.366891,-0.363966,0.215528,2.536792,-0.484571,-0.442050,-0.272758,6.938122,-0.387898,1.0,0.0,1.0,0.0
23969,-0.368421,2,-0.538462,2,2,2,2,2,2,0.102987,0.141471,0.188580,0.237560,0.284815,0.325000,-0.074832,-0.074735,-0.125517,-0.053430,-0.053401,-0.051720,0.0,0.0,1.0,0.0
23970,0.000000,2,-0.153846,1,2,2,2,2,3,0.706785,0.781151,0.823992,1.030006,1.170145,1.220745,0.274383,-0.484571,1.140614,0.667869,0.133502,0.387898,0.0,0.0,1.0,0.0
23971,0.210526,2,0.769231,0,0,0,0,2,0,-0.297861,-0.339244,-0.180352,-0.283111,-0.302356,-0.263549,-0.333999,1.917068,0.406501,-0.400187,0.795408,1.006465,1.0,0.0,1.0,0.0

In [38]:
# find imbalance problem in target col
y.value_counts(normalize= True).round(4) * 100

default.payment.next.month
0    77.87
1    22.13
Name: proportion, dtype: float64

### Machine Learning

### 1) use Logistic Regression model

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

lr = LogisticRegression(random_state=42, n_jobs=-1)

lr.fit(x_train, y_train)

print('Train LR :\n', classification_report(y_train, lr.predict(x_train)))

print('\nTest LR \n:', classification_report(y_test, lr.predict(x_test)))

Train LR :
               precision    recall  f1-score   support

           0       0.83      0.96      0.89     18668
           1       0.69      0.33      0.45      5304

    accuracy                           0.82     23972
   macro avg       0.76      0.65      0.67     23972
weighted avg       0.80      0.82      0.79     23972


Test LR
:               precision    recall  f1-score   support

           0       0.83      0.96      0.89      4667
           1       0.69      0.33      0.45      1326

    accuracy                           0.82      5993
   macro avg       0.76      0.64      0.67      5993
weighted avg       0.80      0.82      0.79      5993

### 1.1) use Logistic Regression model with class weight

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

lr = LogisticRegression(random_state=42, n_jobs=-1, class_weight='balanced')

lr.fit(x_train, y_train)

print('Train LR :\n', classification_report(y_train, lr.predict(x_train)))

print('\nTest LR \n:', classification_report(y_test, lr.predict(x_test)))

Train LR :
               precision    recall  f1-score   support

           0       0.87      0.84      0.86     18668
           1       0.50      0.57      0.53      5304

    accuracy                           0.78     23972
   macro avg       0.69      0.70      0.69     23972
weighted avg       0.79      0.78      0.78     23972


Test LR
:               precision    recall  f1-score   support

           0       0.87      0.84      0.86      4667
           1       0.50      0.55      0.52      1326

    accuracy                           0.78      5993
   macro avg       0.68      0.70      0.69      5993
weighted avg       0.79      0.78      0.78      5993

### 2) KNN classifier 7 neighbors

In [48]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors= 7, n_jobs=-1)

knn.fit(x_train, y_train)

print('Train knn :\n', classification_report(y_train, knn.predict(x_train)))

print('\nTest knn \n:', classification_report(y_test, knn.predict(x_test)))

Train knn :
               precision    recall  f1-score   support

           0       0.85      0.95      0.90     18668
           1       0.71      0.42      0.53      5304

    accuracy                           0.83     23972
   macro avg       0.78      0.69      0.72     23972
weighted avg       0.82      0.83      0.82     23972


Test knn
:               precision    recall  f1-score   support

           0       0.83      0.93      0.88      4667
           1       0.58      0.34      0.43      1326

    accuracy                           0.80      5993
   macro avg       0.70      0.63      0.65      5993
weighted avg       0.78      0.80      0.78      5993

### 3) SVM with class weight

In [50]:
from sklearn.svm import SVC

svc = SVC(class_weight='balanced')

svc.fit(x_train, y_train)

print('Train svc :\n', classification_report(y_train, svc.predict(x_train)))

print('\nTest svc \n:', classification_report(y_test, svc.predict(x_test)))

Train svc :
               precision    recall  f1-score   support

           0       0.88      0.85      0.86     18668
           1       0.52      0.58      0.55      5304

    accuracy                           0.79     23972
   macro avg       0.70      0.71      0.70     23972
weighted avg       0.80      0.79      0.79     23972


Test svc
:               precision    recall  f1-score   support

           0       0.87      0.84      0.86      4667
           1       0.50      0.54      0.52      1326

    accuracy                           0.78      5993
   macro avg       0.68      0.69      0.69      5993
weighted avg       0.78      0.78      0.78      5993

### 4) Gaussian Naive Bayes

In [51]:
from sklearn.naive_bayes import GaussianNB

gaussuan_nb = GaussianNB()

gaussuan_nb.fit(x_train, y_train)

print('Train gaussuan_nb :\n', classification_report(y_train, gaussuan_nb.predict(x_train)))

print('\nTest gaussuan_nb \n:', classification_report(y_test, gaussuan_nb.predict(x_test)))

Train gaussuan_nb :
               precision    recall  f1-score   support

           0       0.87      0.82      0.84     18668
           1       0.47      0.57      0.52      5304

    accuracy                           0.76     23972
   macro avg       0.67      0.69      0.68     23972
weighted avg       0.78      0.76      0.77     23972


Test gaussuan_nb
:               precision    recall  f1-score   support

           0       0.87      0.82      0.84      4667
           1       0.46      0.55      0.50      1326

    accuracy                           0.76      5993
   macro avg       0.66      0.69      0.67      5993
weighted avg       0.78      0.76      0.77      5993

### 5) XGB

In [56]:
from xgboost import XGBClassifier

xgb = XGBClassifier(n_estmotors= 500, max_depth=5, learning_rate=0.05, n_jobs=-1, random_state=42)

xgb.fit(x_train, y_train)

print('Train xgb :\n', classification_report(y_train, xgb.predict(x_train)))

print('\nTest xgb \n:', classification_report(y_test, xgb.predict(x_test)))

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning:

[20:33:11] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "n_estmotors" } are not used.

Train xgb :
               precision    recall  f1-score   support

           0       0.85      0.96      0.90     18668
           1       0.73      0.39      0.51      5304

    accuracy                           0.83     23972
   macro avg       0.79      0.67      0.70     23972
weighted avg       0.82      0.83      0.81     23972


Test xgb
:               precision    recall  f1-score   support

           0       0.84      0.95      0.89      4667
           1       0.67      0.35      0.46      1326

    accuracy                           0.82      5993
   macro avg       0.75      0.65      0.68      5993
weighted avg       0.80      0.82      0.80      5993

In [58]:
# ! pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 7.7 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

### 6) CAT BOOST

In [90]:
from catboost import CatBoostClassifier

cat = CatBoostClassifier(iterations=500, learning_rate=0.1, depth=6, verbose=0)

cat.fit(x_train, y_train)

print('Train cat boost :\n', classification_report(y_train, cat.predict(x_train)))

print('\nTest cat boost \n:', classification_report(y_test, cat.predict(x_test)))

Train cat boost :
               precision    recall  f1-score   support

           0       0.87      0.97      0.92     18668
           1       0.83      0.50      0.62      5304

    accuracy                           0.87     23972
   macro avg       0.85      0.73      0.77     23972
weighted avg       0.86      0.87      0.85     23972


Test cat boost
:               precision    recall  f1-score   support

           0       0.84      0.94      0.89      4667
           1       0.65      0.38      0.48      1326

    accuracy                           0.82      5993
   macro avg       0.75      0.66      0.68      5993
weighted avg       0.80      0.82      0.80      5993

### 6.1) Cat Boost with class weight

In [71]:
from catboost import CatBoostClassifier

cat = CatBoostClassifier(iterations=500, learning_rate=0.1, depth=6, scale_pos_weight = len(y_train[y_train==0]) / len(y_train[y_train==1]), verbose=0)

cat.fit(x_train, y_train)

print('Train cat boost :\n', classification_report(y_train, cat.predict(x_train)))

print('\nTest cat boost \n:', classification_report(y_test, cat.predict(x_test)))

Train cat boost :
               precision    recall  f1-score   support

           0       0.94      0.85      0.89     18668
           1       0.60      0.80      0.68      5304

    accuracy                           0.84     23972
   macro avg       0.77      0.82      0.79     23972
weighted avg       0.86      0.84      0.84     23972


Test cat boost
:               precision    recall  f1-score   support

           0       0.88      0.81      0.84      4667
           1       0.47      0.60      0.53      1326

    accuracy                           0.76      5993
   macro avg       0.68      0.71      0.69      5993
weighted avg       0.79      0.76      0.77      5993

### 6.2) Cat Boost with (SMOTE)

In [94]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

x_train_smote, y_train_smote = smote.fit_resample(x_train, y_train)

cat = CatBoostClassifier(iterations=300, learning_rate=0.1, scale_pos_weight = len(y_train[y_train==0]) / len(y_train[y_train==1]), verbose=0)

cat.fit(x_train_smote, y_train_smote)

print('Train xgb :\n', classification_report(y_train_smote, cat.predict(x_train_smote)))

print('\nTest xgb \n:', classification_report(y_test, cat.predict(x_test)))

Train xgb :
               precision    recall  f1-score   support

           0       0.93      0.69      0.79     18668
           1       0.75      0.95      0.84     18668

    accuracy                           0.82     37336
   macro avg       0.84      0.82      0.81     37336
weighted avg       0.84      0.82      0.81     37336


Test xgb
:               precision    recall  f1-score   support

           0       0.90      0.66      0.76      4667
           1       0.38      0.73      0.50      1326

    accuracy                           0.67      5993
   macro avg       0.64      0.69      0.63      5993
weighted avg       0.78      0.67      0.70      5993

### 6.2) Cat Boost with (over sampling teq)

In [93]:
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)
x_train_ros, y_train_ros = ros.fit_resample(x_train, y_train)

cat = CatBoostClassifier(iterations=500, learning_rate=0.1, verbose=0)

cat.fit(x_train_smote, y_train_smote)

print('Train cat boost :\n', classification_report(y_train_ros, cat.predict(x_train_ros)))

print('\nTest cat boost \n:', classification_report(y_test, cat.predict(x_test)))

Train cat boost :
               precision    recall  f1-score   support

           0       0.66      0.95      0.78     18668
           1       0.92      0.51      0.65     18668

    accuracy                           0.73     37336
   macro avg       0.79      0.73      0.72     37336
weighted avg       0.79      0.73      0.72     37336


Test cat boost
:               precision    recall  f1-score   support

           0       0.84      0.93      0.89      4667
           1       0.63      0.40      0.49      1326

    accuracy                           0.81      5993
   macro avg       0.74      0.66      0.69      5993
weighted avg       0.80      0.81      0.80      5993

### 6.3) Cat Boost with (over_sampling & class weight & threshold) it is the best model

In [117]:
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)
x_train_ros, y_train_ros = ros.fit_resample(x_train, y_train)

cat = CatBoostClassifier(iterations=500, learning_rate=0.01, scale_pos_weight = len(y_train[y_train==0]) / len(y_train[y_train==1]), verbose=0)

cat.fit(x_train_smote, y_train_smote)
# predict propabilty
y_pred_proba = cat.predict_proba(x_test)[:,1]

# apply threshhold manuly
threshold = 0.8
y_pred = (y_pred_proba >= threshold).astype(int)

print('Train cat boost :\n', classification_report(y_train_ros, cat.predict(x_train_ros)))
print('Test cat boost :\n', classification_report(y_test, y_pred))

Train cat boost :
               precision    recall  f1-score   support

           0       0.84      0.31      0.45     18668
           1       0.58      0.94      0.71     18668

    accuracy                           0.62     37336
   macro avg       0.71      0.62      0.58     37336
weighted avg       0.71      0.62      0.58     37336

Test cat boost :
               precision    recall  f1-score   support

           0       0.86      0.87      0.87      4667
           1       0.54      0.52      0.53      1326

    accuracy                           0.79      5993
   macro avg       0.70      0.69      0.70      5993
weighted avg       0.79      0.79      0.79      5993

In [121]:
# to save model
import joblib
joblib.dump({"model": cat, "threshold": threshold}, "catboost_with_threshold.pkl")

['catboost_with_threshold.pkl']

In [ ]:
# to load model
'''
data = joblib.load("catboost_with_threshold.pkl")
cat = data["model"]
threshold = data["threshold"]
# predict propabilty
y_pred_proba = cat.predict_proba(x_test)[:,1]
# apply threshhold manuly
y_pred = (y_pred_proba >= threshold).astype(int)

 '''